# Generated by Django 6.0 on 2025-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_options_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autors',
            field=models.ManyToManyField(related_name='livros', to='core.autor'),
        ),
    ]
