# Generated by Django 6.0 on 2025-12-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_autors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoia',
            new_name='Categoria',
        ),
    ]
