# Generated by Django 6.0 on 2025-12-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_categoia_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autors',
            new_name='autores',
        ),
    ]
