# Generated by Django 6.0 on 2026-01-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itenscompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='desricao',
            new_name='descricao',
        ),
    ]
